### ISSUE TITLE
some problem need to be solved

### ISSUE THREAD

**Issue by LincolnBurrows** [flufy3d/DigitTrak-Interface-Protocol#1]
1. we add 2 commands to protocol.
   {cmd:3 }: set putt mode. 
   {cmd:4 } : set swing mode. 
   default state is swing mode,but if the player is on the green ground need to be set putt mode.if not so ,the small putt can not be detected.
2. we offer the file [DigitTrakMonitor.exe](http://pan.baidu.com/s/1c1ngQbu) ,when the your golf client is launched ,please start a process of it.then connect to it.so we don't need to be start that program manually.
3. {cmd:2} it is no need to send this command every shot ,it means set the device to low-power consumption state .Briefly you could not  send it now,

**Comment by LincolnBurrows** [comment]
haha good morning！

**Comment by sujinlab** [comment]
"{cmd:2} it is no need to send this command every shot ,it means set the device to low-power consumption state .Briefly you could not send it now," 

Do you mean suspend? suspend is cmd:1.

**Comment by sujinlab** [comment]
What is difference between {cmd:0}-ready and {cmd:4}-swingmode? 
Currently, I sended {cmd:0} to start ball detecting.

**Comment by LincolnBurrows** [comment]
SORRY it should be {cmd:1} this command is just for extension later

**Comment by LincolnBurrows** [comment]
the difference between {cmd:0}-ready and {cmd:4}-swingmode:
{cmd:0} is a start signal ,tell 'digittrak' to begin to detect golf ball underground nomatter there is a golfball or not, the default detect mode is swing mode,if you putt golfball our device will not recognize,it think it is misoperation
